"use client";

import React from "react";
import news from "./_lib/news.json";
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { useRouter } from "next/navigation";

const News = () => {
  const router = useRouter();
  // console.log(news);
  return (
    <div className='max-w-6xl mx-auto'>
      <h1 className='scroll-m-20 text-5xl font-extrabold tracking-tight lg:text-5xl'>{news?.title}</h1>
      <div className='mt-4'>
        {news?.modules?.map((module) =>
          module?.stories?.length > 0 ? (
            <Badge className='capitalize text-xs mr-2 mb-2 cursor-pointer' variant={"secondary"}>
              {module?.tracking.title}
            </Badge>
          ) : null
        )}
      </div>
      {/* <Separator className='my-6' /> */}
      <div className='flex  flex-wrap gap-6 my-6'>
        {news?.modules?.map((module) => {
          return module?.stories?.length > 0 ? (
            <>
              <h1 className='w-full text-xl font-semibold'>{module?.tracking.title}</h1>
              {module?.stories?.map((stories) => (
                <Card className='w-72 rounded-lg overflow-clip' onClick={() => router.push(`/news/${stories?.internalID}`)}>
                  {/* <CardHeader className=' space-x-6 space-y-6'> */}
                  <img src={stories?.image} className='w-full h-52 object-cover border-ra' />
                  {/* </CardHeader> */}
                  <CardContent className='px-4 py-6 space-y-2'>
                    <h4 className='scroll-m-20 line-clamp-2 font-semibold tracking-tight'>{stories.title}</h4>
                    <p className='text-sm text-muted-foreground line-clamp-2'>
                      {stories.summary ? stories.summary : stories.autoGeneratedSummary}
                    </p>
                  </CardContent>
                  <CardFooter className='px-4'>
                    {stories?.secondaryBrands?.map((tag) => (
                      <Badge className='capitalize text-xs mr-2' variant={"secondary"}>
                        {tag}
                      </Badge>
                    ))}
                  </CardFooter>
                </Card>
              ))}
              <Separator className='my-4' />
            </>
          ) : null;
        })}
      </div>
    </div>
  );
};

export default News;
