import React from "react";
import newsDetail from "../_lib/news-detail.json";
import { Badge } from "@/components/ui/badge";

const Link: React.FC<{ parts: any }> = ({ parts }) => (
  <>
    {parts.map((part: any, index: any) => {
      return (
        <span className='text-sky-600 cursor-pointer' key={index}>
          {part.text}
        </span>
      );
    })}
  </>
);

const Paragraph: React.FC<{ parts: any }> = ({ parts }) => (
  <p>
    {parts.map((part: any, index: any) => {
      if (part?.parts?.length > 0) return <Link key={index} parts={part.parts} />;
      else return <span key={index}>{part.text}</span>;
    })}
  </p>
);

const Paragraphs: React.FC<{ components: any }> = ({ components }) => (
  <>
    {components.map((component: any, index: any) => (
      <Paragraph key={index} parts={component.parts} />
    ))}
  </>
);
const NewsDetail = () => {
  const ConvertEpoch = (val: number) => new Date(val * 1000)?.toLocaleString();
  return (
    <div className='max-w-6xl mx-auto space-y-6'>
      <h1 className='scroll-m-20 text-5xl font-extrabold tracking-tight lg:text-5xl'>{newsDetail?.title}</h1>
      {/* <div className='flex  flex-wrap gap-6 my-6'>
        {news?.modules?.map((module) => {
          return module?.stories?.length > 0 ? (
            <>
              <h1 className='w-full text-xl font-semibold'>{module?.tracking.title}</h1>
              {module?.stories?.map((stories) => (
                <Card className='w-72 rounded-lg overflow-clip'>
                  <img src={stories?.image} className='w-full h-52 object-cover border-ra' />
                  <CardContent className='px-4 py-6 space-y-2'>
                    <h4 className='scroll-m-20 line-clamp-2 font-semibold tracking-tight'>{stories.title}</h4>
                    <p className='text-sm text-muted-foreground line-clamp-2'>
                      {stories.summary ? stories.summary : stories.autoGeneratedSummary}
                    </p>
                  </CardContent>
                  <CardFooter className='px-4'>
                    {stories?.secondaryBrands?.map((tag) => (
                      <Badge className='capitalize text-xs mr-2' variant={"secondary"}>
                        {tag}
                      </Badge>
                    ))}
                  </CardFooter>
                </Card>
              ))}
              <Separator className='my-4' />
            </>
          ) : null;
        })}
      </div> */}
      <div>
        {newsDetail?.secondaryBrands?.map((tag) => (
          <Badge className='capitalize text-xs mr-2' variant={"secondary"}>
            {tag}
          </Badge>
        ))}
      </div>
      <div>
        <p className='text-foreground/60'>Posted by: {newsDetail?.byline}</p>
        <p className='text-foreground/60'>Posted at: {ConvertEpoch(newsDetail?.published)}</p>
      </div>
      <div className='space-y-4'>
        <Paragraphs components={newsDetail?.components} />
      </div>
    </div>
  );
};

export default NewsDetail;
